version: "1"
services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: docker.n8n.io/n8nio/n8n:latest
    plan: free
    envVars:
      - key: N8N_PUBLIC_API_DISABLED
        value: "false"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "false"
      - key: WEBHOOK_URL
        value: "https://n8n-4uy7.onrender.com/"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_TRUSTED_PROXIES
        value: "loopback,linklocal,uniquelocal"
      - key: DB_SQLITE_POOL_SIZE
        value: "2"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
region: oregon
autoDeployTrigger: commit
