# Exported from Render on 2025-10-21T16:04:52Z
version: "1"
services:
- type: web
  name: n8n
  runtime: image
  image:
    url: docker.n8n.io/n8nio/n8n:latest
  plan: free
  envVars:
  - key: N8N_PUBLIC_API_DISABLED
    sync: false
  region: oregon
  autoDeployTrigger: commit
